### ISSUE TITLE
Trouble getting run-vpn.sh working

### ISSUE THREAD

**Issue by Lolcar84** [peacey/split-vpn#89] opened 2022-03-03 19:05 UTC
Hey there. Thanks for this guide it is extremely helpful getting a VPN up and running on my UDM Pro.

My issue is with getting the background script to run properly. I changed the required information but when executing the command to run the shell. I get an error saying that it could not cd to the appropriate directory. Any help with this would be super.

Also, i might have not noticed but is it possible to have this script jump to another VPN if say one is down? 

Last one, i promise. I was also a little confused on where to put the --auth username and pass command. Any insight on that would be super helpful as well.

**Comment by peacey** [comment] 2022-03-03 21:19
Hi @Lolcar84,

If you rebooted without a VPN boot script, please make sure you run the `setup-split-vpn.sh` script first (just run `/mnt/data/split-vpn/vpn/setup-split-vpn.sh`). The script links split-vpn to /etc directory. If you use a boot script, it will be taken care of automatically. 

After you do that, if you still get any errors running the VPN, please show me the error. 

The `auth-user-pass username_password.txt` option can either be placed in your provider's OpenVPN config (not vpn.conf), or you can add it to the openvpn command line as `--auth-user-pass username_password.txt`.

> Also, i might have not noticed but is it possible to have this script jump to another VPN if say one is down?

That functionality isn't really implemented but obviously can be done, would just require a bit of work. However, if your VPN provider gives you a VPN config with multiple servers, OpenVPN will automatically keep trying a server randomly until it connects if it ever disconnects.

**Comment by Lolcar84** [comment] 2022-03-04 12:28
Thanks for the reply. Still getting the same error even after a reboot and linking to the /etc directory. I'll attach some pics of the error below:
![image](https://user-images.githubusercontent.com/100872155/156763528-0a5f906d-12e9-4366-afbd-3f38ae7937bb.jpeg)

Password advice worked like a charm!

**Comment by peacey** [comment] 2022-03-04 16:09
It seems like something is wrong with your run-vpn.sh script. There could be two issues. 

1. Double check the run-vpn.sh has the correct shebang at the top and you didn't miss any characters: `#!/bin/sh` 
2. Did you create it locally on the UDM, or on your computer and then transferred it over? If you created it on your computer, you might get encoding issues. Try to create it locally with vim instead. 

If it still doesn't work, please show me the contents of your run-vpn script.

**Comment by netfxtech** [comment] 2022-03-13 10:23
not sure if it's required but I typically chmod +x my scripts and make sure your on_boot.d folder has the correct scripts in it.

**Comment by Lolcar84** [comment] 2022-03-19 09:20
Sorry for the late reply! Been hella swamped. I was able to get everything up and running. Using vim to get the script to run was the solution. I was being lazy and typing it out then trying to drag and drop it onto the router with WinSCP. That's for all the help!

**Comment by peacey** [comment] 2022-03-19 16:19
No problem! Glad you got it working. Closing this now as the issue is fixed. If you have any more issues, feel free to re-open!

**Closed by peacey** 2022-03-19 16:19 UTC
